package com.panda.mapper;

import com.panda.pojo.UserDb;

public interface UserDbMapper {
    /*通过username查找一条记录*/
    UserDb selectByUserName(String UserName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdb
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdb
     *
     * @mbggenerated
     */
    int insert(UserDb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdb
     *
     * @mbggenerated
     */
    int insertSelective(UserDb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdb
     *
     * @mbggenerated
     */
    UserDb selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdb
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserDb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userdb
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserDb record);
}