package com.panda.pojo;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sql_user.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sql_user.uname
     *
     * @mbggenerated
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sql_user.uage
     *
     * @mbggenerated
     */
    private Integer uage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sql_user.gender
     *
     * @mbggenerated
     */
    private String gender;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sql_user
     *
     * @mbggenerated
     */
    public User(Integer id, String uname, Integer uage, String gender) {
        this.id = id;
        this.uname = uname;
        this.uage = uage;
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sql_user
     *
     * @mbggenerated
     */
    public User() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sql_user.id
     *
     * @return the value of sql_user.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sql_user.id
     *
     * @param id the value for sql_user.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sql_user.uname
     *
     * @return the value of sql_user.uname
     *
     * @mbggenerated
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sql_user.uname
     *
     * @param uname the value for sql_user.uname
     *
     * @mbggenerated
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sql_user.uage
     *
     * @return the value of sql_user.uage
     *
     * @mbggenerated
     */
    public Integer getUage() {
        return uage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sql_user.uage
     *
     * @param uage the value for sql_user.uage
     *
     * @mbggenerated
     */
    public void setUage(Integer uage) {
        this.uage = uage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sql_user.gender
     *
     * @return the value of sql_user.gender
     *
     * @mbggenerated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sql_user.gender
     *
     * @param gender the value for sql_user.gender
     *
     * @mbggenerated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", uname='" + uname + '\'' +
                ", uage=" + uage +
                ", gender='" + gender + '\'' +
                '}';
    }
}